// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BlazorAspNetFactory.Shared.Models;

#nullable disable

namespace BlazorAspNetFactory.Shared.Data
{
    public partial class TestedbContext : DbContext
    {
        public TestedbContext()
        {
        }

        public TestedbContext(DbContextOptions<TestedbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Teste1> Teste1 { get; set; }
        public virtual DbSet<Teste2> Teste2 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Teste1>(entity =>
            {
                entity.Property(e => e.Teste1id).HasColumnName("teste1id");

                entity.Property(e => e.Inteiro).HasColumnName("inteiro");

                entity.Property(e => e.String)
                    .HasMaxLength(255)
                    .HasColumnName("string");
            });

            modelBuilder.Entity<Teste2>(entity =>
            {
                entity.Property(e => e.Teste2id).HasColumnName("teste2id");

                entity.Property(e => e.Inteiro).HasColumnName("inteiro");

                entity.Property(e => e.String)
                    .HasMaxLength(255)
                    .HasColumnName("string");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}