// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorAspNetFactory.Shared.Models
{
    public partial class Teste2
    {
        public int Teste2id { get; set; }
        public int? Inteiro { get; set; }
        public string String { get; set; }
    }
}